apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-stack-operator-grafana-operator
  namespace: grafana-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: monitoring-stack-operator-grafana-operator
      containers:
        - name: grafana-operator
          args:
            - --metrics-bind-address=127.0.0.1:8080
            - --zap-log-level=error
            - --scan-all
          command:
            - /manager
          image: quay.io/grafana-operator/grafana-operator:v4.0.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "grafana-operator"
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
          terminationMessagePolicy: FallbackToLogsOnError
