apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: grafana-operator
    app.kubernetes.io/part-of: monitoring-stack-monitoring
  name: monitoring-stack-operator-grafana-operator
