resources:
- clusterrolebindings.yaml
- deployment.yaml
- prometheus-operator-cluster-role.yaml
- grafana-operator-cluster-role.yaml
- role.yaml
- serviceaccount.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: monitoring-stack-operator
  newTag: 0.0.2
