
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: monitoring-stack-operator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - list
- apiGroups:
  - ""
  resourceNames:
  - monitoring-stack-operator
  resources:
  - namespaces
  verbs:
  - get
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks/finalizers
  - monitoringstacks/status
  verbs:
  - get
  - update
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks/status
  verbs:
  - get
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: monitoring-stack-operator
  namespace: monitoring-stack-operator
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - operatorgroups
  - subscriptions
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
