
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: monitoring-stack-operator
rules:
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks/finalizers
  - monitoringstacks/status
  verbs:
  - get
  - update
